# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Aaaazdy\Desktop\物联网信息处理\第四章作业\lab 4\ImageMiniLabUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageMiniLabUI(object):
    def setupUi(self, ImageMiniLabUI):
        ImageMiniLabUI.setObjectName("ImageMiniLabUI")
        ImageMiniLabUI.resize(1333, 558)
        self.centralwidget = QtWidgets.QWidget(ImageMiniLabUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ImgShowWidget = QtWidgets.QWidget(self.centralwidget)
        self.ImgShowWidget.setObjectName("ImgShowWidget")
        self.SrcImgShowLabel = QtWidgets.QLabel(self.ImgShowWidget)
        self.SrcImgShowLabel.setGeometry(QtCore.QRect(35, 11, 120, 16))
        self.SrcImgShowLabel.setObjectName("SrcImgShowLabel")
        self.DstImgShowLabel = QtWidgets.QLabel(self.ImgShowWidget)
        self.DstImgShowLabel.setGeometry(QtCore.QRect(130, 100, 120, 16))
        self.DstImgShowLabel.setObjectName("DstImgShowLabel")
        self.gridLayout.addWidget(self.ImgShowWidget, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.GoExpPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.GoExpPushButton.setObjectName("GoExpPushButton")
        self.gridLayout.addWidget(self.GoExpPushButton, 1, 0, 1, 1)
        self.LabCtrlWidget = QtWidgets.QWidget(self.centralwidget)
        self.LabCtrlWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.LabCtrlWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.LabCtrlWidget.setObjectName("LabCtrlWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LabCtrlWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.LabCtrlWidget)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ExpTypeComboBox = QtWidgets.QComboBox(self.LabCtrlWidget)
        self.ExpTypeComboBox.setObjectName("ExpTypeComboBox")
        self.horizontalLayout_2.addWidget(self.ExpTypeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.LabCtrlWidget)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.ExpImgLineEdit = QtWidgets.QLineEdit(self.LabCtrlWidget)
        self.ExpImgLineEdit.setEnabled(True)
        self.ExpImgLineEdit.setObjectName("ExpImgLineEdit")
        self.horizontalLayout_3.addWidget(self.ExpImgLineEdit)
        self.SelectImgPushButton = QtWidgets.QPushButton(self.LabCtrlWidget)
        self.SelectImgPushButton.setObjectName("SelectImgPushButton")
        self.horizontalLayout_3.addWidget(self.SelectImgPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.LoadTestDataPushButton = QtWidgets.QPushButton(self.LabCtrlWidget)
        self.LoadTestDataPushButton.setObjectName("LoadTestDataPushButton")
        self.verticalLayout.addWidget(self.LoadTestDataPushButton)
        self.line_2 = QtWidgets.QFrame(self.LabCtrlWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.LabCtrlWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(30, 30, 261, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(110, 0, 91, 21))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.LabCtrlWidget, 0, 0, 1, 1)
        ImageMiniLabUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageMiniLabUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1333, 34))
        self.menubar.setObjectName("menubar")
        ImageMiniLabUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageMiniLabUI)
        self.statusbar.setObjectName("statusbar")
        ImageMiniLabUI.setStatusBar(self.statusbar)

        self.retranslateUi(ImageMiniLabUI)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageMiniLabUI)

    def retranslateUi(self, ImageMiniLabUI):
        _translate = QtCore.QCoreApplication.translate
        ImageMiniLabUI.setWindowTitle(_translate("ImageMiniLabUI", "ImageMiniLab"))
        self.SrcImgShowLabel.setText(_translate("ImageMiniLabUI", "SrcImgShowLabel"))
        self.DstImgShowLabel.setText(_translate("ImageMiniLabUI", "DstImgShowLabel"))
        self.GoExpPushButton.setText(_translate("ImageMiniLabUI", "进行实验"))
        self.label_2.setText(_translate("ImageMiniLabUI", "实验类型："))
        self.label_3.setText(_translate("ImageMiniLabUI", "实验图片："))
        self.SelectImgPushButton.setText(_translate("ImageMiniLabUI", "选择"))
        self.LoadTestDataPushButton.setText(_translate("ImageMiniLabUI", "重载测试数据"))
        self.label.setText(_translate("ImageMiniLabUI", "程序输出"))
